# Generated by Django 2.2.1 on 2019-06-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('CMA', models.IntegerField()),
                ('Phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zipcode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=20)),
                ('Urbanization', models.CharField(max_length=50)),
            ],
        ),
    ]
